name: takeout_app
description: Takeout app.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0

  path_provider: ^2.0.9
  audio_session: ^0.1.6+1
  audio_service: ^0.18.3
  just_audio: ^0.9.20
  just_audio_libwinmedia: ^0.0.4
  rxdart: ^0.27.1

  video_player: ^2.2.6
  wakelock: ^0.6.1+1

  timeago: ^3.1.0
  timeago_flutter: ^1.2.0

  shared_preferences: ^2.0.6
  json_annotation: ^4.7.0
  cached_network_image: ^3.0.0
  connectivity_plus: ^3.0.2
  palette_generator: ^0.3.0
  recase: ^4.0.0
  url_launcher: ^6.0.2
  flutter_settings_screens: ^0.3.0-null-safety
  sqflite: ^2.2.0+3

  cupertino_icons: ^1.0.3

  webview_flutter: ^4.0.1

  dynamic_color: ^1.1.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  generate: true
