name: takeout_app
description: Takeout app.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  path_provider: ^2.0.2
  audio_session: ^0.1.6+1
  audio_service: ^0.18.1
  just_audio: ^0.9.16
  just_audio_libwinmedia: ^0.0.4
  rxdart: ^0.27.1

  video_player: ^2.2.6
  wakelock: ^0.5.6

  timeago: ^3.1.0

  shared_preferences: ^2.0.6
  json_annotation: ^4.0.1
  cached_network_image: ^3.0.0
  connectivity: ^3.0.2
  palette_generator: ^0.3.0
  recase: ^4.0.0
  url_launcher: ^6.0.2
  flutter_settings_screens: ^0.3.0-null-safety

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  generate: true
