name: takeout_app
description: Takeout app.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  takeout_lib:
    path: ../takeout_lib/

  cupertino_icons: ^1.0.3
  dynamic_color: ^1.1.2
  flutter_bloc: ^8.1.1
  json_annotation: ^4.8.0
  recase: ^4.0.0
  rxdart: ^0.27.1
  timeago: ^3.1.0
  timeago_flutter: ^1.2.0
  url_launcher: ^6.0.2
  video_player: ^2.2.6
  wakelock: ^0.6.1+1
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
