name: takeout_lib
description: Takeout Library
version: 0.11.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.9
  audio_session: ^0.1.14
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1
  logging: ^1.1.1
  json_annotation: ^4.8.0
  just_audio: ^0.9.33
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.15
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
