name: takeout_lib
description: Takeout Library
version: 0.10.5
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.3
  audio_session: ^0.1.6+1
  cached_network_image: ^3.0.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  logging: ^1.1.1
  json_annotation: ^4.8.0
  just_audio: ^0.9.20
  palette_generator: ^0.3.0
  path_provider: ^2.0.9
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
